POST http://127.0.0.1:8000/users/create_user/
Content-Type: application/json

{
    "username": "sdsdsd",
    "password": "dsfsdf",
    "email": ""
}

###

GET http://127.0.0.1:8000/users/get_user/5
Content-Type: application/json


