# Generated by Django 4.2.5 on 2023-09-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_product_available_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
